# Upstream changes from _extends are only recognized when modifications are made to this file in the default branch.
_extends: .github
repository:
  name: aws-lambda
  description: This component is responsible for provisioning Lambda functions
  homepage: https://cloudposse.com/accelerate
  topics: terraform, terraform-component










